export interface Ward {
    name: string;
    zipCode: string;
}

export interface City {
    name: string;
    wards: Ward[];
}

export const VN_LOCATIONS: City[] = [
    {
        name: "Ho Chi Minh City",
        wards: [
            {name: "Sai Gon Ward", zipCode: "700101"},
            {name: "Tan Dinh Ward", zipCode: "700102"},
            {name: "Ben Thanh Ward", zipCode: "700103"},
            {name: "Cau Ong Lanh Ward", zipCode: "700104"},
            {name: "Ban Co Ward", zipCode: "700105"},
            {name: "Xuan Hoa Ward", zipCode: "700106"},
            {name: "Nhieu Loc Ward", zipCode: "700107"},
            {name: "Xom Chieu Ward", zipCode: "700108"},
            {name: "Khanh Hoi Ward", zipCode: "700109"},
            {name: "Vinh Hoi Ward", zipCode: "700110"},
            {name: "Cho Quan Ward", zipCode: "700111"},
            {name: "An Dong Ward", zipCode: "700112"},
            {name: "Cho Lon Ward", zipCode: "700113"},
            {name: "Binh Tay Ward", zipCode: "700114"},
            {name: "Binh Tien Ward", zipCode: "700115"},
            {name: "Binh Phu Ward", zipCode: "700116"},
            {name: "Phu Lam Ward", zipCode: "700117"},
            {name: "Tan Thuan Ward", zipCode: "700118"},
            {name: "Phu Thuan Ward", zipCode: "700119"},
            {name: "Tan My Ward", zipCode: "700120"},
            {name: "Tan Hung Ward", zipCode: "700121"},
            {name: "Chanh Hung Ward", zipCode: "700122"},
            {name: "Phu Dinh Ward", zipCode: "700123"},
            {name: "Binh Dong Ward", zipCode: "700124"},
            {name: "Dien Hong Ward", zipCode: "700125"},
            {name: "Vuon Lai Ward", zipCode: "700126"},
            {name: "Hoa Hung Ward", zipCode: "700127"},
            {name: "Minh Phung Ward", zipCode: "700128"},
            {name: "Binh Thoi Ward", zipCode: "700129"},
            {name: "Hoa Binh Ward", zipCode: "700130"},
            {name: "Phu Tho Ward", zipCode: "700131"},
            {name: "Dong Hung Thuan Ward", zipCode: "700132"},
            {name: "Trung My Tay Ward", zipCode: "700133"},
            {name: "Tan Thoi Hiep Ward", zipCode: "700134"},
            {name: "Thoi An Ward", zipCode: "700135"},
            {name: "An Phu Dong Ward", zipCode: "700136"},
            {name: "An Lac Ward", zipCode: "700137"},
            {name: "Binh Tan Ward", zipCode: "700138"},
            {name: "Tan Tao Ward", zipCode: "700139"},
            {name: "Binh Tri Dong Ward", zipCode: "700140"},
            {name: "Binh Hung Hoa Ward", zipCode: "700141"},
            {name: "Gia Dinh Ward", zipCode: "700142"},
            {name: "Binh Thanh Ward", zipCode: "700143"},
            {name: "Binh Loi Trung Ward", zipCode: "700144"},
            {name: "Thanh My Tay Ward", zipCode: "700145"},
            {name: "Binh Quoi Ward", zipCode: "700146"},
            {name: "Hanh Thong Ward", zipCode: "700147"},
            {name: "An Nhon Ward", zipCode: "700148"},
            {name: "Go Vap Ward", zipCode: "700149"},
            {name: "An Hoi Dong Ward", zipCode: "700150"},
            {name: "Thong Tay Hoi Ward", zipCode: "700151"},
            {name: "An Hoi Tay Ward", zipCode: "700152"},
            {name: "Duc Nhuan Ward", zipCode: "700153"},
            {name: "Cau Kieu Ward", zipCode: "700154"},
            {name: "Phu Nhuan Ward", zipCode: "700155"},
            {name: "Tan Son Hoa Ward", zipCode: "700156"},
            {name: "Tan Son Nhat Ward", zipCode: "700157"},
            {name: "Tan Hoa Ward", zipCode: "700158"},
            {name: "Bay Hien Ward", zipCode: "700159"},
            {name: "Tan Binh Ward", zipCode: "700160"},
            {name: "Tan Son Ward", zipCode: "700161"},
            {name: "Tay Thanh Ward", zipCode: "700162"},
            {name: "Tan Son Nhi Ward", zipCode: "700163"},
            {name: "Phu Tho Hoa Ward", zipCode: "700164"},
            {name: "Tan Phu Ward", zipCode: "700165"},
            {name: "Phu Thanh Ward", zipCode: "700166"},
            {name: "Hiep Binh Ward", zipCode: "700167"},
            {name: "Thu Duc Ward", zipCode: "700168"},
            {name: "Tam Binh Ward", zipCode: "700169"},
            {name: "Linh Xuan Ward", zipCode: "700170"},
            {name: "Tang Nhon Phu Ward", zipCode: "700171"},
            {name: "Long Binh Ward", zipCode: "700172"},
            {name: "Long Phuoc Ward", zipCode: "700173"},
            {name: "Long Truong Ward", zipCode: "700174"},
            {name: "Cat Lai Ward", zipCode: "700175"},
            {name: "Binh Trung Ward", zipCode: "700176"},
            {name: "Phuoc Long Ward", zipCode: "700177"},
            {name: "An Khanh Ward", zipCode: "700178"}
        ]
    }
];