package edu.hcmute;

import edu.hcmute.outbound.UserOutboundApi;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
class UserMgmtServiceApplicationTests {
    @Autowired
    private UserOutboundApi userOutboundApi;

    @Test
    public void testGetAllUsers() {
        String token = "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI0S2FKVEdKRWxMS0N0ZHc1SVFrOEJ6OGRCd2tmQmVnR3lEd1NZVEhOWFpJIn0.eyJleHAiOjE3NTkzMjY0MDIsImlhdCI6MTc1OTMyNDYwMiwianRpIjoidHJydGNjOjg3NzkxY2U2LWJiZGItM2NkNS05YzNmLTA5MTRlNmNkMDNhNyIsImlzcyI6Imh0dHA6Ly8xMjcuMC4wLjE6ODA4MS9yZWFsbXMvcGljbWEiLCJhdWQiOlsicmVhbG0tbWFuYWdlbWVudCIsImFjY291bnQiXSwic3ViIjoiYTk1NGZlNDgtYWYxNy00MjcwLWE0NWUtNjQ4ZmY3Nzc5YmZlIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiYmFvdmlldC1pbnN1cmVyIiwiYWNyIjoiMSIsImFsbG93ZWQtb3JpZ2lucyI6WyIvKiJdLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsib2ZmbGluZV9hY2Nlc3MiLCJkZWZhdWx0LXJvbGVzLXBpY21hIiwidW1hX2F1dGhvcml6YXRpb24iXX0sInJlc291cmNlX2FjY2VzcyI6eyJyZWFsbS1tYW5hZ2VtZW50Ijp7InJvbGVzIjpbIm1hbmFnZS11c2VycyJdfSwiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJwcm9maWxlIGVtYWlsIiwiY2xpZW50SG9zdCI6IjE3Mi4xOC4wLjEiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6InNlcnZpY2UtYWNjb3VudC1iYW92aWV0LWluc3VyZXIiLCJjbGllbnRBZGRyZXNzIjoiMTcyLjE4LjAuMSIsImNsaWVudF9pZCI6ImJhb3ZpZXQtaW5zdXJlciJ9.GQMDPdk5TimrVjq88McuFdPScxckFqh9JBMh9jACbTiKS55UR6ynPiV9h3r5H5-rvYVTAWvklSjcICFApxxaPwQ8-r6Wcv-jRh7ljY6l8ELzDHQgh89K9jvm3B9kLML7t-lJcwamamItlMkjRyNR9zIBkEhBsJgwdZ3StUIxNRzV88-D5TjwM0SShQUC6JsXzRpCEm06btGHwdf-vAKpufO81PV9o_CxXAZX1i7TW5D9tnHCJFjzjCaurh6OJSuEfzX-zSACL4aLL2HDQBkXW3e9CyfkbYiDlDEzOK0xzaaLbN0r4CirqF8tADtMXiGRvwtod71eeVijONU_Fxyqhg";
        userOutboundApi.getAllPropertyOwners(token);
    }

    @Test
    void contextLoads() {
    }
}