package edu.hcmute;

import edu.hcmute.outbound.UserOutboundApi;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

import java.net.URISyntaxException;

@SpringBootTest
class UserMgmtServiceApplicationTests {
    @Autowired
    private UserOutboundApi userOutboundApi;

    @Test
    public void testGetAllUsers() throws URISyntaxException {
        String token = "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI0S2FKVEdKRWxMS0N0ZHc1SVFrOEJ6OGRCd2tmQmVnR3lEd1NZVEhOWFpJIn0.eyJleHAiOjE3NTkzMDI3ODcsImlhdCI6MTc1OTMwMDk4NywianRpIjoidHJydGNjOmZmY2M5N2Q5LThkNzEtN2M5Yy0wMTU5LWU0MmQzN2NkZTk3NSIsImlzcyI6Imh0dHA6Ly8xMjcuMC4wLjE6ODA4MS9yZWFsbXMvcGljbWEiLCJhdWQiOlsicmVhbG0tbWFuYWdlbWVudCIsImFjY291bnQiXSwic3ViIjoiYTk1NGZlNDgtYWYxNy00MjcwLWE0NWUtNjQ4ZmY3Nzc5YmZlIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiYmFvdmlldC1pbnN1cmVyIiwiYWNyIjoiMSIsImFsbG93ZWQtb3JpZ2lucyI6WyIvKiJdLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsib2ZmbGluZV9hY2Nlc3MiLCJkZWZhdWx0LXJvbGVzLXBpY21hIiwidW1hX2F1dGhvcml6YXRpb24iXX0sInJlc291cmNlX2FjY2VzcyI6eyJyZWFsbS1tYW5hZ2VtZW50Ijp7InJvbGVzIjpbIm1hbmFnZS11c2VycyJdfSwiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJwcm9maWxlIGVtYWlsIiwiY2xpZW50SG9zdCI6IjE3Mi4xOC4wLjEiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6InNlcnZpY2UtYWNjb3VudC1iYW92aWV0LWluc3VyZXIiLCJjbGllbnRBZGRyZXNzIjoiMTcyLjE4LjAuMSIsImNsaWVudF9pZCI6ImJhb3ZpZXQtaW5zdXJlciJ9.U_rIcEg6azwZHKU-cukl2t89RIm9DOG8thHKKitH99xL_fgtsP_bCco4DylUfZRfnBTm3t8a4ZTQ8iJbdzb7so0UBkAnkFs2PnksOItqHlPUCHC6uTV8Tbm62y-74unbFqbv08WunC4vsaeMFvu47O-jrYXwC5YNI3gyG1tBqQBptBxgJ63M7D4lmPg9FLOY0iEZWvdL0zJFAGQeP1jV0uopFWjIiQ8ERS-m-FeC4KxuqnxjwBq2n1redoa89dvoBzod8JfruQydFFTAAywxiPiIwponSvHZMMxctE7ehiPyh-8LipEO1ZQpqzD8Yt0Ht-5qViVy6tyTTSbCf7_AQA";
        userOutboundApi.getAllPropertyOwners(token);
    }

    @Test
    void contextLoads() {
    }
}